### ISSUE TITLE
deep-hough build error

### ISSUE THREAD

**Issue by ZhouYangUSTC** [Hanqer/deep-hough-transform#25]
按照readme步骤构建deep-hough模块，发生了一个错误，请问该怎么解决？
错误信息：

```
1 error detected in the compilation of "C:/Users/yang/AppData/Local/Temp/tmpxft_00001858_00000000-10_deep_hough_cuda_kernel.cpp1.ii".
deep_hough_cuda_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1517, in _run_ninja_build
    subprocess.run(
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 654, in build_extensions
    build_ext.build_extensions(self)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial    self.build_extension(ext)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 627, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1234, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\ProgramFile\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by Hanqer** [comment]
您好，这个脚本没有在windows平台上测试过编译，您可以使用ubuntu系统来进行相关的实验。

**Comment by ZhouYangUSTC** [comment]
> 您好，这个脚本没有在windows平台上测试过编译，您可以使用ubuntu系统来进行相关的实验。

哈哈，好的。非常感谢。

**Comment by ZhouYangUSTC** [comment]
另外，有没有考率支持win10系统？

**Comment by zeakey** [comment]
windows 上的工具链相对比较麻烦，Linux 上的工具链更加完整，网上的资料也更多。我们没有支持 windows 的计划。

**Comment by HassanBinHaroon** [comment]
@ZhouYangUSTC   Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
