### ISSUE TITLE
Error encountered while compiling and installing the "deep-hough" module.

### ISSUE THREAD

**Issue by hungryDodo** [Hanqer/deep-hough-transform#35]
Thank you for your excellent work.

I'm having problems configuring the runtime environment for the code in the repository according to the [Requirements](https://github.com/Hanqer/deep-hough-transform#requirements).
During the installation of the `deep-hough` module by compiling the `model/_cdht`, I encountered the following error:

```
1 error detected in the compilation of "C:/Users/Dodo/Desktop/deep-hough-transform/model/_cdht/deep_hough_cuda_kernel.cu".
deep_hough_cuda_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\dht\lib\site-packages\torch\utils\cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "D:\ProgramData\Anaconda3\envs\nanodet\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

...

RuntimeError: Error compiling objects for extension
```

After some preliminary troubleshooting, it seems to be due to a version mismatch between `ninja` and `pytorch`.
I am running this code in Windows system.

What is your version number? Could you please tell me if you have encountered this problem? 

Again, my respects.

**Comment by Hanqer** [comment]
I think the trouble is not the version between `ninja` and `PyTorch`. We use `pytorch>=1.3 and <= 1.6` and default ninja in Ubuntu16/18. Currently, I do not try compiling it on Windows system, all experiments are conducted in Linux/ Unbuntu system.

**Comment by HassanBinHaroon** [comment]
@hungryDodo  You can follow the following Github repository to reproduce the work on pretrained or NKL and SEL datasets (hopefully without any error). The implementation is on Google Colab and you can run it from anywhere.

It successfully installs the ninja library. 

https://github.com/HassanBinHaroon/deep-hough-transform

**Comment by laborer123** [comment]
> Thank you for your excellent work.
> 
> I'm having problems configuring the runtime environment for the code in the repository according to the [Requirements](https://github.com/Hanqer/deep-hough-transform#requirements). During the installation of the module by compiling the , I encountered the following error:`deep-hough``model/_cdht`
> 
> ```
> 1 error detected in the compilation of "C:/Users/Dodo/Desktop/deep-hough-transform/model/_cdht/deep_hough_cuda_kernel.cu".
> deep_hough_cuda_kernel.cu
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "D:\ProgramData\Anaconda3\envs\dht\lib\site-packages\torch\utils\cpp_extension.py", line 1516, in _run_ninja_build
>     subprocess.run(
>   File "D:\ProgramData\Anaconda3\envs\nanodet\lib\subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> ...
> 
> RuntimeError: Error compiling objects for extension
> ```
> 
> After some preliminary troubleshooting, it seems to be due to a version mismatch between and . I am running this code in Windows system.`ninja``pytorch`
> 
> What is your version number? Could you please tell me if you have encountered this problem?
> 
> Again, my respects.

Did you solve the problem? I also use it on windows
