### ISSUE TITLE
Error encountered while compiling and installing the "deep-hough" module.

### ISSUE THREAD

**Issue by iifeve** [Hanqer/deep-hough-transform#38]
Hey there, thanks for your excellent work,  I'm trying to recur this paper, and this problem occurs, during the installation of deep-hough module.

```

D:\files\python\deep-hough-transform-master\model\_cdht> setup.py install --user
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1'
running install
running bdist_egg
running egg_info
writing deep_hough.egg-info\PKG-INFO
writing dependency_links to deep_hough.egg-info\dependency_links.txt
writing top-level names to deep_hough.egg-info\top_level.txt
C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using th
e slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'deep_hough.egg-info\SOURCES.txt'
writing manifest file 'deep_hough.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "D:\files\python\deep-hough-transform-master\model\_cdht\setup.py", line 4, in <module>
    setup(
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 410, in build_extensions
    self._check_cuda_version()
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 783, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
  File "C:\Users\iif_s\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
``` 

It seems like there is something wrong with setuptools.

I have seen the another issue which encountered similar problem. I wander if there would be alternatives for Windows?

And again thanks for your work.

**Comment by Hanqer** [comment]
Hi, currently the code is not supported for windows. You can use a pure Ubuntu system to reproduce our semantic line detection that only installs CUDA and pytorch.

**Comment by iifeve** [comment]
would you mind to check the cuda and pytorch version, It seems require the library cudatoolkit 11.0, which doesn't match the pytorch version 1.3~1.6

**Comment by Hanqer** [comment]
We use cuda9/10 with pytorch 1.3~1.6.  It not require cuda11.

**Comment by HassanBinHaroon** [comment]
@iifeve You can **follow the following Github repository** to reproduce the work on pretrained or NKL and SEL datasets (hopefully **without any error**). The implementation is on **Google Colab** and you can run it from anywhere. 

https://github.com/HassanBinHaroon/deep-hough-transform

**Comment by Surajj4837-th** [comment]
I m also facing the same issue. I m using Ubuntu 20.04.
